### ISSUE TITLE
Standardize, organize and define the purpose of each file

### ISSUE THREAD

**Issue by ET33** [ET33/socket-stream-io#2]
As it is today, there's no description of what `server.c`, `client.c` and `main.c` should do. Leave your sugestions here

**Comment by BrunoxD** [comment]
My suggestion is to transfer all the code of `client.c` into functions at `sockets.c`, therefore `main.c` will become the new `server.c` and the old `server.c` will be turn into `sockets.c`.

Thus, all the functions in `sockets.c` and `sockets.h` will be shared between `client.c` and `server.c` since they need several common functions to define and operate a socket connection.

**Comment by ET33** [comment]
Why can't we leave the `main()` function within `server.c` and `client.c`? Dunno if it is a bad practice, but still makes sense to me.
Alternatively, we could simply use: `server.c`, `server_main.c` and `client.c`, `client_main.c`.

I don't think the server and the client will have that many functions in common other than `send_data()` and `receive_data()`.

Notice that in both cases we would have 2 executable files, for server side and for the client.

**Comment by BrunoxD** [comment]
To take advantage of reuse of code. I'm not talking about `send_data()` or `receive_data()`, I'm talking about functions that is used to create the socket .

Please, look at [the branch](https://github.com/ET33/socket-stream-io/tree/Standarize/solomon) to better understand what I'm talking about.

**Comment by ET33** [comment]
As this subject was decided in #3 and #4, I'm gonna close it for now
